// import { PrismaClient } from "@prisma/client";
// ✅ Add these two lines instead
import pkg from "@prisma/client";
const { PrismaClient } = pkg;
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import dotenv from "dotenv";
import { logger } from "./logger.js";
dotenv.config();

// --- 1. ENVIRONMENT CONFIGURATION ---
const dbConnection =
  process.env.NODE_ENV === "test"
    ? process.env.DATABASE_URL_TEST
    : process.env.DATABASE_URL;

if (!dbConnection) {
  logger.error(
    "Database connection string is not found in the environment variables",
  );
  process.exit(1);
}

// --- 2. THE CONNECTION POOL (The Tollbooth) ---
// Instead of opening a brand new connection for every single user request,
// the Pool keeps a small batch of connections permanently open and reuses them.
// This is critical for performance and prevents the database from crashing under load.
const pool = new pg.Pool({
  connectionString: dbConnection,
});

// --- 3. THE ADAPTER (The Translator) ---
// Prisma 7 removed its built-in database driver to be faster and lighter.
// This adapter takes the raw SQL generated by Prisma and hands it to the 'pg' pool to actually execute.
const adapter = new PrismaPg(pool);

// --- 4. THE PRISMA CLIENT (The Engine) ---
// The globalThis object survives Nodemon server restarts during local development.
// We check if a connection already exists before creating a new one.
// This prevents memory leaks from opening hundreds of pools every time we hit 'Save'.
const prisma =
  globalThis.prisma ||
  new PrismaClient({
    adapter,
  });

if (process.env.NODE_ENV !== "production") {
  globalThis.prisma = prisma; // Save the instance for the next Nodemon restart
}

logger.info(
  `Prisma Client initialized for ${process.env.NODE_ENV === "test" ? "Test" : "Main"} environment`,
);

export default prisma;

/**
 * Graceful shutdown helper
 * ------------------------
 * Prisma's `$disconnect()` stops Prisma's internal resources. Because we're using an external
 * `pg.Pool` via the Prisma adapter, we also end the pool to release all open sockets.
 */
export async function disconnectPrisma() {
  await prisma.$disconnect();
  await pool.end();
}
